# Generated by Django 3.2.1 on 2021-06-01 13:14

# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('tr_ars', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.AddField(
#             model_name='actor',
#             name='active',
#             field=models.BooleanField(default=True, verbose_name='actor is active'),
#         ),
#     ]