# # Generated by Django 3.2.9 on 2021-11-09 18:20
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('tr_ars', '0002_actor_active'),
#     ]
#
#     operations = [
#         migrations.RemoveField(
#             model_name='actor',
#             name='remote',
#         ),
#         migrations.AddField(
#             model_name='actor',
#             name='inforesid',
#             field=models.CharField(blank=True, max_length=500, verbose_name='inforesid'),
#         ),
#     ]