# # Generated by Django 3.2.4 on 2022-05-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0003_auto_20211109_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='result_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
