# Generated by Django 3.1.3 on 2023-01-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0004_auto_20220524_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='result_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
