# Generated by Django 3.2.4 on 2022-11-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0004_auto_20220524_1908'),
    ]

    operations = [
    ]
