# Generated by Django 3.1.3 on 2023-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0007_alter_message_result_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='retain',
            field=models.BooleanField(default=False, verbose_name='flag to retain data'),
        ),
    ]
