# Generated by Django 3.2.23 on 2024-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0010_message_merged_versions_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.BinaryField(null=True, verbose_name='data payload'),
        ),
    ]
