# Generated by Django 3.2.23 on 2024-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0011_alter_message_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='params',
            field=models.JSONField(null=True),
        ),
    ]
