# Generated by Django 3.2.23 on 2025-01-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0012_message_params'),
    ]

    operations = [
    ]
