# Generated by Django 3.2.23 on 2025-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0013_auto_20250113_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_secret_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscriptions',
            field=models.JSONField(blank=True, null=True, verbose_name='List of pks to which a client is curently subscribed'),
        ),
        migrations.AlterField(
            model_name='message',
            name='clients',
            field=models.ManyToManyField(related_name='messages', to='tr_ars.Client'),
        ),
    ]
