# Generated by Django 3.2.23 on 2025-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0014_auto_20250121_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryGraphPlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_graph', models.JSONField(null=True)),
                ('stats', models.JSONField(null=True)),
            ],
        ),
    ]
