# Generated by Django 3.2.23 on 2025-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_ars', '0015_querygraphplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='querygraphplus',
            name='num_res',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='querygraphplus',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('S', 'Stopped'), ('R', 'Running'), ('E', 'Error'), ('W', 'Waiting'), ('U', 'Unknown')], db_index=True, default='R', max_length=2),
        ),
    ]
