language: python
script: python server.py test
install:
  - pip install -r requirements.txt
before_script:
  - python tr_sys/manage.py makemigrations tr_ars
  - python tr_sys/manage.py migrate
  - python tr_sys/manage.py runserver --noreload &
  - sleep 10 # give some time for server to come up
