FROM python:3.9-buster

ENV PYTHONUNBUFFERED=1
WORKDIR /ars
RUN apt-get update && apt install -y netcat
RUN pip install --no-cache-dir newrelic
RUN newrelic-admin generate-config NewRelic_KEY newrelic.ini

COPY requirements.txt /ars/
RUN pip install -r requirements.txt
COPY . /ars/
RUN mv wait-for /bin/wait-for
