apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ars.fullname" . }}-settings
  labels:
    {{- include "ars.labels" . | nindent 4 }}
data:
  settings.py: |
{{ .Files.Get "files/settings.py" | indent 4 }}
