{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ars.fullname" . }}-secrets
  labels:
    {{- include "ars.labels" . | nindent 4 }}
type: Opaque
stringData:
  django-secret-key: {{ .Values.secrets.djangoSecretKey | quote }}
  aes-master-key: {{ .Values.secrets.aesMasterKey | quote }}
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | quote }}
{{- end }}
