apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Values.appname }}-config-1
  labels:
    {{- include "ars.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "configs/*.cnf").AsConfig | nindent 2 }}
