apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: ars
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.arsserver.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appname }}