name: 'Pull Request Feedback'

on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache tox environments
        uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ runner.os }}-${{ hashFiles('tox.ini', 'requirements*.txt') }}
          restore-keys: |
            tox-${{ runner.os }}-

      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox


      - name: Run tests
        run: tox
